name: blog-build
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ablog
  - sphinx
  - sphinx-reredirects
  - sphinx-intl
  - pre-commit
  - IPython
  - nbsphinx
  - pip:
    - pydata_sphinx_theme
    - sphinx-design
