name: blog-build
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ablog
  - sphinx<7
  - sphinx-reredirects
  - sphinx-intl
  - pre-commit
  - IPython
  - nbsphinx
  - sphinxcontrib-youtube
  - pip:
    - pydata_sphinx_theme
    - sphinx-design
    - git+https://github.com/ferrine/sphinx-carousel.git@gettext-fix
