# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Github Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
      - name: Print Env Config
        run: pip freeze
      - name: Build the Blog
        run: make checklinks html
      - name: Check Content Size
        run: du -h build/html
      - name: Compress the Blog source
        run: tar -C build/html -cvf build/html.tar.gz .
      - name: Store Build Content
        uses: actions/upload-artifact@v3
        with:
          name: website-content
          path: build/html.tar.gz

  preview:
    runs-on: ubuntu-latest
    needs: [html]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: website-content
      - name: Unpack Build Content
        run: |
          tar -xvf html.tar.gz
          rm html.tar.gz
      - name: Deploy site preview to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: .
          production-deploy: ${{ github.ref == 'refs/heads/main' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
