# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Github Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true
      - uses: abatilo/actions-poetry@v2
      - name: Build the Blog
        run: make checklinks html
      - name: Store Build Content
        uses: actions/upload-artifact@v3
        with:
          name: website-content
          path: build/html

  preview:
    runs-on: ubuntu-latest
    needs: [html]
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: website-content
      - name: Deploy site preview to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: .
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
