# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Github Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
      - name: Print Env Config
        run: pip freeze
      - name: Build the Blog
        run: make html
      - name: Store Build Content
        uses: actions/upload-artifact@v3
        with:
          name: website-content
          path: build/html
